import type { Course, StudentProfile } from '@/types';

export const defaultProfile: StudentProfile = {
  name: '',
  level: '',
  age: '',
  gender: '',
  matric: '',
  phone: '',
  state: '',
  school: '',
  department: '',
  courses: [],
};

const sampleQuestions = {
  mathematics: [
    { q: 'What is the derivative of x³ with respect to x?', options: ['3x²', 'x²', '3x', 'x³'], answer: 0, explanation: 'Using the power rule: d/dx(xⁿ) = nxⁿ⁻¹, so d/dx(x³) = 3x²' },
    { q: 'Solve for x: 2x + 5 = 15', options: ['5', '10', '7.5', '20'], answer: 0, explanation: '2x + 5 = 15 → 2x = 10 → x = 5' },
    { q: 'What is the value of sin(30°)?', options: ['1/2', '√3/2', '√2/2', '1'], answer: 0, explanation: 'sin(30°) = 1/2 = 0.5' },
    { q: 'Find the integral of 2x dx', options: ['x² + C', '2x² + C', 'x + C', '2 + C'], answer: 0, explanation: '∫2x dx = x² + C using the power rule for integration' },
    { q: 'What is the sum of the interior angles of a triangle?', options: ['180°', '360°', '90°', '270°'], answer: 0, explanation: 'The sum of interior angles of any triangle is always 180°' },
    { q: 'If f(x) = x² - 4x + 4, what is f(2)?', options: ['0', '4', '8', '2'], answer: 0, explanation: 'f(2) = (2)² - 4(2) + 4 = 4 - 8 + 4 = 0' },
    { q: 'What is the value of log₁₀(100)?', options: ['2', '10', '100', '1'], answer: 0, explanation: 'log₁₀(100) = 2 because 10² = 100' },
    { q: 'Solve: x² - 5x + 6 = 0', options: ['x = 2 or 3', 'x = -2 or -3', 'x = 1 or 6', 'x = -1 or -6'], answer: 0, explanation: 'Factoring: (x-2)(x-3) = 0, so x = 2 or x = 3' },
    { q: 'What is the slope of the line y = 3x + 2?', options: ['3', '2', '1/3', '-3'], answer: 0, explanation: 'In y = mx + c form, m is the slope, so slope = 3' },
    { q: 'Find the area of a circle with radius 4 units', options: ['16π', '8π', '4π', '32π'], answer: 0, explanation: 'Area = πr² = π(4)² = 16π' },
    { q: 'What is the value of cos(60°)?', options: ['1/2', '√3/2', '0', '1'], answer: 0, explanation: 'cos(60°) = 1/2 = 0.5' },
    { q: 'If a = 3 and b = 4, what is √(a² + b²)?', options: ['5', '7', '25', '12'], answer: 0, explanation: '√(3² + 4²) = √(9 + 16) = √25 = 5' },
    { q: 'What is the factorial of 5 (5!)?', options: ['120', '25', '15', '50'], answer: 0, explanation: '5! = 5 × 4 × 3 × 2 × 1 = 120' },
    { q: 'Solve for x: |x - 3| = 5', options: ['x = 8 or -2', 'x = 5 or -5', 'x = 3 or -3', 'x = 2 or 8'], answer: 0, explanation: '|x - 3| = 5 means x - 3 = 5 or x - 3 = -5, so x = 8 or x = -2' },
    { q: 'What is the median of {3, 1, 7, 5, 9}?', options: ['5', '3', '7', '1'], answer: 0, explanation: 'Sorted: {1, 3, 5, 7, 9}, middle value is 5' },
  ],
  physics: [
    { q: 'What is the SI unit of force?', options: ['Newton (N)', 'Joule (J)', 'Watt (W)', 'Pascal (Pa)'], answer: 0, explanation: 'The Newton (N) is the SI unit of force. 1 N = 1 kg·m/s²' },
    { q: 'What is the acceleration due to gravity on Earth?', options: ['9.8 m/s²', '10 m/s²', '8.9 m/s²', '9.2 m/s²'], answer: 0, explanation: 'Standard gravity is approximately 9.8 m/s² downward' },
    { q: 'Which law states that every action has an equal and opposite reaction?', options: ['Newton\'s Third Law', 'Newton\'s First Law', 'Newton\'s Second Law', 'Law of Gravitation'], answer: 0, explanation: 'Newton\'s Third Law: For every action, there is an equal and opposite reaction' },
    { q: 'What is the formula for kinetic energy?', options: ['½mv²', 'mgh', 'mv', 'ma'], answer: 0, explanation: 'Kinetic Energy = ½ × mass × velocity²' },
    { q: 'What type of wave is light?', options: ['Electromagnetic', 'Mechanical', 'Sound', 'Water'], answer: 0, explanation: 'Light is an electromagnetic wave that does not require a medium' },
    { q: 'What is the speed of light in vacuum?', options: ['3 × 10⁸ m/s', '3 × 10⁶ m/s', '3 × 10⁵ m/s', '3 × 10⁷ m/s'], answer: 0, explanation: 'c ≈ 3 × 10⁸ m/s (299,792,458 m/s exactly)' },
    { q: 'What is Ohm\'s Law?', options: ['V = IR', 'P = VI', 'I = V/R', 'R = V+I'], answer: 0, explanation: 'Ohm\'s Law: Voltage = Current × Resistance' },
    { q: 'What is the unit of electrical resistance?', options: ['Ohm (Ω)', 'Ampere (A)', 'Volt (V)', 'Coulomb (C)'], answer: 0, explanation: 'Resistance is measured in Ohms (Ω)' },
    { q: 'What happens to the pressure of a gas if its volume decreases at constant temperature?', options: ['Increases', 'Decreases', 'Stays the same', 'Becomes zero'], answer: 0, explanation: 'Boyle\'s Law: P ∝ 1/V at constant temperature' },
    { q: 'What is the first law of thermodynamics about?', options: ['Conservation of energy', 'Entropy increase', 'Heat flow', 'Temperature'], answer: 0, explanation: 'First Law: Energy cannot be created or destroyed, only transferred or converted' },
  ],
  chemistry: [
    { q: 'What is the chemical symbol for gold?', options: ['Au', 'Ag', 'Gd', 'Go'], answer: 0, explanation: 'Au comes from the Latin word \'aurum\' meaning gold' },
    { q: 'What is the pH of pure water at 25°C?', options: ['7', '0', '14', '1'], answer: 0, explanation: 'Pure water is neutral with a pH of 7 at standard temperature' },
    { q: 'What type of bond involves the sharing of electron pairs?', options: ['Covalent', 'Ionic', 'Metallic', 'Hydrogen'], answer: 0, explanation: 'Covalent bonds involve sharing of electron pairs between atoms' },
    { q: 'What is the most abundant gas in Earth\'s atmosphere?', options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'], answer: 0, explanation: 'Nitrogen makes up about 78% of Earth\'s atmosphere' },
    { q: 'What is the molecular formula of glucose?', options: ['C₆H₁₂O₆', 'C₆H₆O₆', 'C₁₂H₂₂O₁₁', 'CH₂O'], answer: 0, explanation: 'Glucose has the molecular formula C₆H₁₂O₆' },
    { q: 'What is Avogadro\'s number?', options: ['6.022 × 10²³', '6.022 × 10²²', '3.022 × 10²³', '9.8 × 10²³'], answer: 0, explanation: 'Avogadro\'s number = 6.022 × 10²³ particles per mole' },
    { q: 'What is the charge of an electron?', options: ['-1', '+1', '0', '-2'], answer: 0, explanation: 'An electron has a negative charge of -1 elementary charge' },
    { q: 'Which element has the atomic number 1?', options: ['Hydrogen', 'Helium', 'Lithium', 'Carbon'], answer: 0, explanation: 'Hydrogen is the lightest element with atomic number 1' },
  ],
  biology: [
    { q: 'What is the powerhouse of the cell?', options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus'], answer: 0, explanation: 'Mitochondria produce ATP through cellular respiration' },
    { q: 'What is the basic unit of life?', options: ['Cell', 'Tissue', 'Organ', 'Molecule'], answer: 0, explanation: 'The cell is the basic structural and functional unit of all living organisms' },
    { q: 'What process do plants use to convert light energy to chemical energy?', options: ['Photosynthesis', 'Respiration', 'Fermentation', 'Digestion'], answer: 0, explanation: 'Photosynthesis converts CO₂ and H₂O into glucose using sunlight' },
    { q: 'What molecule carries genetic information?', options: ['DNA', 'RNA', 'Protein', 'Lipid'], answer: 0, explanation: 'DNA (Deoxyribonucleic acid) carries genetic instructions' },
    { q: 'What is the largest organ in the human body?', options: ['Skin', 'Liver', 'Brain', 'Heart'], answer: 0, explanation: 'The skin is the largest organ, covering about 2 square meters' },
    { q: 'How many chromosomes do humans have?', options: ['46', '23', '44', '48'], answer: 0, explanation: 'Humans have 46 chromosomes (23 pairs) in each somatic cell' },
    { q: 'What blood type is the universal donor?', options: ['O negative', 'AB positive', 'A positive', 'B negative'], answer: 0, explanation: 'O negative can be donated to any blood type' },
    { q: 'What is the process of cell division called?', options: ['Mitosis', 'Meiosis', 'Binary fission', 'Budding'], answer: 0, explanation: 'Mitosis produces two identical daughter cells' },
  ],
  english: [
    { q: 'Which of the following is a metaphor?', options: ['Time is money', 'He runs like a cheetah', 'She is as busy as a bee', 'The wind howled'], answer: 0, explanation: '\'Time is money\' directly equates two things without using \'like\' or \'as\'' },
    { q: 'What is the past tense of "go"?', options: ['Went', 'Gone', 'Going', 'Goes'], answer: 0, explanation: '\'Went\' is the simple past tense of \'go\'' },
    { q: 'Which word is a synonym of "happy"?', options: ['Joyful', 'Sad', 'Angry', 'Tired'], answer: 0, explanation: '\'Joyful\' means full of joy, similar to happy' },
    { q: 'What is the correct spelling?', options: ['Accommodation', 'Acomodation', 'Accomodation', 'Acommodation'], answer: 0, explanation: 'Accommodation has two c\'s and two m\'s' },
    { q: 'Which is an example of alliteration?', options: ['Peter Piper picked', 'The sky is blue', 'He runs fast', 'She sings well'], answer: 0, explanation: '\'Peter Piper picked\' repeats the \'p\' sound' },
    { q: 'What is the antonym of "generous"?', options: ['Selfish', 'Kind', 'Giving', 'Charitable'], answer: 0, explanation: '\'Selfish\' is the opposite of generous' },
    { q: 'Which sentence is in passive voice?', options: ['The cake was eaten by the dog', 'The dog ate the cake', 'The dog eats cake', 'The dog will eat cake'], answer: 0, explanation: 'The subject (cake) receives the action in passive voice' },
    { q: 'What part of speech is "quickly"?', options: ['Adverb', 'Adjective', 'Noun', 'Verb'], answer: 0, explanation: '\'Quickly\' describes how an action is performed, making it an adverb' },
  ],
  economics: [
    { q: 'What is the basic economic problem?', options: ['Scarcity', 'Inflation', 'Unemployment', 'Growth'], answer: 0, explanation: 'Scarcity is the fundamental problem of unlimited wants vs limited resources' },
    { q: 'What does GDP stand for?', options: ['Gross Domestic Product', 'General Domestic Product', 'Gross Development Product', 'General Development Product'], answer: 0, explanation: 'GDP = Gross Domestic Product, the total value of goods/services produced' },
    { q: 'What is inflation?', options: ['General rise in prices', 'Fall in employment', 'Increase in exports', 'Decrease in demand'], answer: 0, explanation: 'Inflation is a sustained increase in the general price level' },
    { q: 'What type of market has many buyers and sellers?', options: ['Perfect competition', 'Monopoly', 'Oligopoly', 'Monopsony'], answer: 0, explanation: 'Perfect competition has many buyers and sellers with no market power' },
    { q: 'What is the law of demand?', options: ['Price up, quantity demanded down', 'Price up, quantity demanded up', 'Price down, supply up', 'Income up, demand down'], answer: 0, explanation: 'Law of Demand: As price increases, quantity demanded decreases' },
    { q: 'What is opportunity cost?', options: ['Value of next best alternative', 'Total cost of production', 'Cost of raw materials', 'Fixed cost'], answer: 0, explanation: 'Opportunity cost is what you give up to choose something else' },
    { q: 'What does the central bank control?', options: ['Monetary policy', 'Fiscal policy', 'Trade policy', 'Labor policy'], answer: 0, explanation: 'Central banks control monetary policy (interest rates, money supply)' },
    { q: 'What is a budget deficit?', options: ['Spending exceeds revenue', 'Revenue exceeds spending', 'Balanced spending', 'No spending'], answer: 0, explanation: 'Budget deficit occurs when government spending exceeds revenue' },
  ],
  'computer science': [
    { q: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Computer Processing Unit'], answer: 0, explanation: 'CPU = Central Processing Unit, the brain of the computer' },
    { q: 'What is the binary representation of 5?', options: ['101', '110', '100', '111'], answer: 0, explanation: '5 in decimal = 101 in binary (4 + 0 + 1)' },
    { q: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Language', 'Home Tool Markup Language'], answer: 0, explanation: 'HTML = HyperText Markup Language, used for web pages' },
    { q: 'What is the time complexity of binary search?', options: ['O(log n)', 'O(n)', 'O(n²)', 'O(1)'], answer: 0, explanation: 'Binary search divides the search space in half each time: O(log n)' },
    { q: 'What is a stack data structure?', options: ['LIFO', 'FIFO', 'Random access', 'Sequential'], answer: 0, explanation: 'Stack is Last-In-First-Out (LIFO)' },
    { q: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Language', 'Standard Query Language', 'System Query Language'], answer: 0, explanation: 'SQL = Structured Query Language for database management' },
    { q: 'What is the default port for HTTP?', options: ['80', '443', '8080', '22'], answer: 0, explanation: 'HTTP uses port 80 by default, HTTPS uses 443' },
    { q: 'What is an IP address?', options: ['Unique network identifier', 'Website name', 'File path', 'Password'], answer: 0, explanation: 'An IP address uniquely identifies a device on a network' },
  ],
  accounting: [
    { q: 'What is the accounting equation?', options: ['Assets = Liabilities + Equity', 'Assets = Liabilities - Equity', 'Assets + Liabilities = Equity', 'Assets - Liabilities = Revenue'], answer: 0, explanation: 'The fundamental accounting equation: Assets = Liabilities + Owner\'s Equity' },
    { q: 'What is depreciation?', options: ['Decrease in asset value', 'Increase in revenue', 'Payment to creditors', 'Cash inflow'], answer: 0, explanation: 'Depreciation is the systematic allocation of an asset\'s cost over its useful life' },
    { q: 'What is a balance sheet?', options: ['Statement of financial position', 'Income statement', 'Cash flow statement', 'Trial balance'], answer: 0, explanation: 'A balance sheet shows assets, liabilities, and equity at a point in time' },
    { q: 'What does debit mean?', options: ['Left side of account', 'Right side of account', 'Increase only', 'Decrease only'], answer: 0, explanation: 'Debit refers to the left side of a T-account' },
    { q: 'What is working capital?', options: ['Current assets - Current liabilities', 'Total assets - Total liabilities', 'Fixed assets + Current assets', 'Revenue - Expenses'], answer: 0, explanation: 'Working capital = Current assets - Current liabilities' },
    { q: 'What is a trial balance?', options: ['List of all account balances', 'Final financial statement', 'Bank statement', 'Audit report'], answer: 0, explanation: 'A trial balance lists all ledger accounts and their balances' },
  ],
};

export function getDemoCourses(): Course[] {
  return [
    {
      id: 'math',
      subject: 'Mathematics',
      icon: '🔢',
      questions: sampleQuestions.mathematics,
    },
    {
      id: 'phys',
      subject: 'Physics',
      icon: '⚡',
      questions: sampleQuestions.physics,
    },
    {
      id: 'chem',
      subject: 'Chemistry',
      icon: '🧪',
      questions: sampleQuestions.chemistry,
    },
    {
      id: 'bio',
      subject: 'Biology',
      icon: '🧬',
      questions: sampleQuestions.biology,
    },
    {
      id: 'eng',
      subject: 'English Language',
      icon: '📖',
      questions: sampleQuestions.english,
    },
    {
      id: 'econ',
      subject: 'Economics',
      icon: '📊',
      questions: sampleQuestions.economics,
    },
    {
      id: 'cs',
      subject: 'Computer Science',
      icon: '💻',
      questions: sampleQuestions['computer science'],
    },
    {
      id: 'acct',
      subject: 'Accounting',
      icon: '📒',
      questions: sampleQuestions.accounting,
    },
  ];
}
